[Typescript] Increased size limits for some deps (#3728)
# Description of Changes

<!-- Please describe your change, mention any related tickets, and so on
here. -->

We got some errors when publishing the typescript release related to the
size limits of these deps. This PR just increases those limits.

```
  cjs (brotli)
  Package size limit has exceeded by 348 B
  Size limit: 25 kB
  Size:       25.35 kB brotlied
  
  esm (brotli)
  Package size limit has exceeded by 5.19 kB
  Size limit: 20 kB
  Size:       25.19 kB brotlied
  
  esm (gzip)
  Package size limit has exceeded by 4.63 kB
  Size limit: 25 kB
  Size:       29.63 kB gzipped
  
  esm (uncompressed)
  Package size limit has exceeded by 8.45 kB
  Size limit: 150 kB
  Size:       158.45 kB
  
  esm min (brotli)
  Package size limit has exceeded by 1.65 kB
  Size limit: 12 kB
  Size:       13.65 kB brotlied
  
  esm min (gzip)
  Package size limit has exceeded by 490 B
  Size limit: 15 kB
  Size:       15.49 kB gzipped
  
  esm min (uncompressed)
  Package size limit has exceeded by 3.51 kB
  Size limit: 60 kB
  Size:       63.51 kB
  
  react esm min (brotli)
  Size limit: 10 kB
  Size:       4.13 kB brotlied
  
  react esm min (uncompressed)
  Size limit: 10 kB
  Size:       4.13 kB brotlied
  
  react esm min (gzip)
  Size limit: 15 kB
  Size:       4.64 kB gzipped
  
  sdk esm min (brotli)
  Package size limit has exceeded by 3.41 kB
  Size limit: 10 kB
  Size:       13.41 kB brotlied
  
  sdk esm min (gzip)
  Package size limit has exceeded by 251 B
  Size limit: 15 kB
  Size:       15.25 kB gzipped
  
  sdk esm min (uncompressed)
  Package size limit has exceeded by 3.41 kB
  Size limit: 10 kB
  Size:       13.41 kB brotlied
  
  Try to reduce size or increase limit in "size-limit" section of package.json
 ELIFECYCLE  Command failed with exit code 1.
 ELIFECYCLE  Command failed with exit code 1.
Error: Failed to publish package to npm
Error: Process completed with exit code 1.
```

# API and ABI breaking changes

None

<!-- If this is an API or ABI breaking change, please apply the
corresponding GitHub label. -->

# Expected complexity level and risk

1 - This just fixes the release.

<!--
How complicated do you think these changes are? Grade on a scale from 1
to 5,
where 1 is a trivial change, and 5 is a deep-reaching and complex
change.

This complexity rating applies not only to the complexity apparent in
the diff,
but also to its interactions with existing and future code.

If you answered more than a 2, explain what is complex about the PR,
and what other components it interacts with in potentially concerning
ways. -->

# Testing

- I have not tested this because I want review before trying it on the
release.

<!-- Describe any testing you've done, and any testing you'd like your
reviewers to do,
so that you're confident that all the changes work as expected! -->